
//call "Release\CPrime.exe" - config "vs2017.h" 

#pragma source "config.h"
#pragma source "Mem.h"
#pragma source "Mem.c"
#pragma source "Result.h"
#pragma source "Array.h"
#pragma source "Array.c"
#pragma source "List.h"
#pragma source "LocalStrBuilder.h"
#pragma source "LocalStrBuilder.c"
#pragma source "Ast.h"
#pragma source "Ast.c"
#pragma source "AstPrint.h"
#pragma source "AstPrint.c"
#pragma source "BasicScanner.h"
#pragma source "BasicScanner.c"
#pragma source "CodePrint.h"
#pragma source "CodePrint.c"
#pragma source "CPrime.c"
#pragma source "Macro.h"
#pragma source "Macro.c"
#pragma source "Map.c"
#pragma source "Map.h"
#pragma source "Map2.h"
#pragma source "Map2.c"
#pragma source "Parser.h"
#pragma source "Parser.c"
#pragma source "Path.h"
#pragma source "Path.c"
#pragma source "PPToken.h"
#pragma source "PPToken.c"
#pragma source "Scanner.h"
#pragma source "Scanner.c"
#pragma source "StrBuilder.h"
#pragma source "StrBuilder.c"
#pragma source "Stream.h"
#pragma source "Stream.c"
#pragma source "StringEx.h"
#pragma source "StringEx.c"
#pragma source "SymbolMap.h"
#pragma source "SymbolMap.c"
#pragma source "TokenArray.h"
#pragma source "TokenArray.c"
#pragma source "amalgamation.h"
#pragma source "amalgamation.c"

//#if UNIT_TEST
//#pragma source "UnitTest.c"
//#pragma source "UnitTest.h"

//#endif



